<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.desperis.advancements</groupId>
    <artifactId>better-advancements</artifactId>
    <version>1.0.0</version>
    <inceptionYear>2025</inceptionYear>
    <packaging>jar</packaging>

    <properties>
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <developers>
        <developer>
            <id>Despical</id>
            <name>Berke Akçen</name>
            <email>berkeakcen@gmail.com</email>
            <url>https://www.spigotmc.org/members/615094/</url>
            <organization>Desperis Creations</organization>
            <organizationUrl>https://github.com/DesperisCreations</organizationUrl>
        </developer>
    </developers>

    <profiles>
        <profile>
            <id>Despical</id>
            <activation>
                <property>
                    <name>user.name</name>
                    <value>berke</value>
                </property>
            </activation>
            <build>
                <directory>${project.basedir}/build-berke</directory>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jar-plugin</artifactId>
                        <configuration>
                            <outputDirectory>C:/Users/berke/OneDrive/Masaüstü/1.21.4 Server/plugins/</outputDirectory>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <repositories>
        <repository>
            <id>papermc</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>fren_gor</id>
            <url>https://nexus.frengor.com/repository/public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.destroystokyo.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.16.5-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.Despical</groupId>
            <artifactId>Commons</artifactId>
            <version>1.9.1</version>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>com.github.Despical</groupId>-->
<!--            <artifactId>CommandFramework</artifactId>-->
<!--            <version>1.5.13</version>-->
<!--        </dependency>-->
        <dependency>
            <groupId>com.frengor</groupId>
            <artifactId>ultimateadvancementapi-shadeable</artifactId>
            <version>2.4.3</version>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <goals>
                    <goal>compile</goal>
                </goals>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <archive>
                        <addMavenDescriptor>false</addMavenDescriptor>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.3</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
<!--                            <minimizeJar>true</minimizeJar>-->
                            <relocations>
<!--                                <relocation>-->
<!--                                    <pattern>me.despical.commandframework</pattern>-->
<!--                                    <shadedPattern>io.greenmc.survivalgames.commands</shadedPattern>-->
<!--                                </relocation>-->
                            </relocations>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/**</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>