general:
  default-language: en
  cache-save-interval-seconds: 60
  hidden-achievement-placeholder: "<dark_gray>???</dark_gray>"

notifications:
  chat: true
  title: true
  action-bar: true
  boss-bar: true
  sound: UI_TOAST_CHALLENGE_COMPLETE