name: BetterAdvancements
version: ${version}
main: dev.erissos.betteradvancements.BetterAdvancementsPlugin
api-version: '1.20'
authors: [Erissos]
description: Premium configurable advancement framework with GUI, rewards, challenges and leaderboards.
softdepend: [Vault, PlaceholderAPI]
libraries:
  - com.zaxxer:HikariCP:5.1.0
  - org.xerial:sqlite-jdbc:3.45.3.0
  - com.mysql:mysql-connector-j:8.4.0
commands:
  ba:
    description: Better Advancements main command
    usage: /ba <menu|stats|leaderboard|challenges|season|prestige|reload|give|reset|language>
    aliases: [betteradvancements]
permissions:
  ba.use:
    default: true
  ba.admin:
    default: op