name: BetterAdvancements
version: ${version}
main: dev.erissos.betteradvancements.BetterAdvancementsPlugin
api-version: '1.20'
authors: [Erissos]
description: Premium configurable advancement framework with GUI, rewards, challenges and leaderboards.
softdepend: [Vault, PlaceholderAPI]
commands:
  ba:
    description: Better Advancements main command
    usage: /ba <menu|stats|leaderboard|reload|give|reset|language>
    aliases: [betteradvancements]
permissions:
  ba.use:
    default: true
  ba.admin:
    default: op